namespace SkyTakeout_WinForm
{
    partial class UcCategoryManage
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.panelRoot = new System.Windows.Forms.Panel();
            this.panelTable = new System.Windows.Forms.Panel();
            this.dataGridViewCategory = new System.Windows.Forms.DataGridView();
            this.colSelect = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.colName = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colType = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colSort = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colStatus = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colUpdateTime = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colEdit = new System.Windows.Forms.DataGridViewLinkColumn();
            this.colDelete = new System.Windows.Forms.DataGridViewLinkColumn();
            this.colToggle = new System.Windows.Forms.DataGridViewLinkColumn();
            this.panelPager = new System.Windows.Forms.Panel();
            this.comboBoxPageSize = new System.Windows.Forms.ComboBox();
            this.labelPage = new System.Windows.Forms.Label();
            this.buttonNext = new System.Windows.Forms.Button();
            this.buttonPrev = new System.Windows.Forms.Button();
            this.labelTotal = new System.Windows.Forms.Label();
            this.panelFilter = new System.Windows.Forms.Panel();
            this.panelActions = new System.Windows.Forms.Panel();
            this.buttonAddSetmealCategory = new System.Windows.Forms.Button();
            this.buttonAddDishCategory = new System.Windows.Forms.Button();
            this.buttonBatchDelete = new System.Windows.Forms.Button();
            this.buttonSearch = new System.Windows.Forms.Button();
            this.comboBoxStatus = new System.Windows.Forms.ComboBox();
            this.labelStatus = new System.Windows.Forms.Label();
            this.comboBoxType = new System.Windows.Forms.ComboBox();
            this.labelType = new System.Windows.Forms.Label();
            this.textBoxCategoryName = new System.Windows.Forms.TextBox();
            this.labelCategoryName = new System.Windows.Forms.Label();
            this.panelRoot.SuspendLayout();
            this.panelTable.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewCategory)).BeginInit();
            this.panelPager.SuspendLayout();
            this.panelFilter.SuspendLayout();
            this.panelActions.SuspendLayout();
            this.SuspendLayout();
            this.panelRoot.BackColor = System.Drawing.Color.White;
            this.panelRoot.Controls.Add(this.panelTable);
            this.panelRoot.Controls.Add(this.panelPager);
            this.panelRoot.Controls.Add(this.panelFilter);
            this.panelRoot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelRoot.Location = new System.Drawing.Point(0, 0);
            this.panelRoot.Name = "panelRoot";
            this.panelRoot.Padding = new System.Windows.Forms.Padding(16);
            this.panelRoot.Size = new System.Drawing.Size(1000, 680);
            this.panelRoot.TabIndex = 0;
            this.panelTable.Controls.Add(this.dataGridViewCategory);
            this.panelTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelTable.Location = new System.Drawing.Point(16, 76);
            this.panelTable.Name = "panelTable";
            this.panelTable.Size = new System.Drawing.Size(968, 548);
            this.panelTable.TabIndex = 2;
            this.dataGridViewCategory.AllowUserToAddRows = false;
            this.dataGridViewCategory.AllowUserToDeleteRows = false;
            this.dataGridViewCategory.AllowUserToResizeRows = false;
            this.dataGridViewCategory.BackgroundColor = System.Drawing.Color.White;
            this.dataGridViewCategory.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridViewCategory.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridViewCategory.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(49)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(49)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridViewCategory.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dataGridViewCategory.ColumnHeadersHeight = 44;
            this.dataGridViewCategory.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dataGridViewCategory.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.colSelect,
            this.colName,
            this.colType,
            this.colSort,
            this.colStatus,
            this.colUpdateTime,
            this.colEdit,
            this.colDelete,
            this.colToggle});
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(49)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(246)))), ((int)(((byte)(247)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(49)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridViewCategory.DefaultCellStyle = dataGridViewCellStyle2;
            this.dataGridViewCategory.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataGridViewCategory.EnableHeadersVisualStyles = false;
            this.dataGridViewCategory.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(238)))), ((int)(((byte)(245)))));
            this.dataGridViewCategory.Location = new System.Drawing.Point(0, 0);
            this.dataGridViewCategory.MultiSelect = false;
            this.dataGridViewCategory.Name = "dataGridViewCategory";
            this.dataGridViewCategory.RowHeadersVisible = false;
            this.dataGridViewCategory.RowHeadersWidth = 62;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            this.dataGridViewCategory.RowsDefaultCellStyle = dataGridViewCellStyle3;
            this.dataGridViewCategory.RowTemplate.Height = 52;
            this.dataGridViewCategory.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridViewCategory.Size = new System.Drawing.Size(968, 548);
            this.dataGridViewCategory.TabIndex = 0;
            this.colSelect.FillWeight = 36F;
            this.colSelect.HeaderText = "";
            this.colSelect.MinimumWidth = 36;
            this.colSelect.Name = "colSelect";
            this.colSelect.Width = 36;
            this.colName.FillWeight = 140F;
            this.colName.HeaderText = "分类名称";
            this.colName.MinimumWidth = 120;
            this.colName.Name = "colName";
            this.colName.ReadOnly = true;
            this.colName.Width = 140;
            this.colType.FillWeight = 120F;
            this.colType.HeaderText = "分类类型";
            this.colType.MinimumWidth = 100;
            this.colType.Name = "colType";
            this.colType.ReadOnly = true;
            this.colType.Width = 120;
            this.colSort.FillWeight = 80F;
            this.colSort.HeaderText = "排序";
            this.colSort.MinimumWidth = 70;
            this.colSort.Name = "colSort";
            this.colSort.ReadOnly = true;
            this.colSort.Width = 80;
            this.colStatus.FillWeight = 80F;
            this.colStatus.HeaderText = "状态";
            this.colStatus.MinimumWidth = 80;
            this.colStatus.Name = "colStatus";
            this.colStatus.ReadOnly = true;
            this.colStatus.Width = 80;
            this.colUpdateTime.FillWeight = 160F;
            this.colUpdateTime.HeaderText = "操作时间";
            this.colUpdateTime.MinimumWidth = 140;
            this.colUpdateTime.Name = "colUpdateTime";
            this.colUpdateTime.ReadOnly = true;
            this.colUpdateTime.Width = 160;
            this.colEdit.FillWeight = 55F;
            this.colEdit.HeaderText = "操作";
            this.colEdit.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(158)))), ((int)(((byte)(255)))));
            this.colEdit.MinimumWidth = 50;
            this.colEdit.Name = "colEdit";
            this.colEdit.Text = "修改";
            this.colEdit.UseColumnTextForLinkValue = true;
            this.colEdit.Width = 55;
            this.colDelete.FillWeight = 55F;
            this.colDelete.HeaderText = "";
            this.colDelete.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(108)))), ((int)(((byte)(108)))));
            this.colDelete.MinimumWidth = 50;
            this.colDelete.Name = "colDelete";
            this.colDelete.Text = "删除";
            this.colDelete.UseColumnTextForLinkValue = true;
            this.colDelete.Width = 55;
            this.colToggle.FillWeight = 70F;
            this.colToggle.HeaderText = "";
            this.colToggle.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(98)))), ((int)(((byte)(102)))));
            this.colToggle.MinimumWidth = 60;
            this.colToggle.Name = "colToggle";
            this.colToggle.Text = "禁用";
            this.colToggle.UseColumnTextForLinkValue = true;
            this.colToggle.Width = 70;
            this.panelPager.Controls.Add(this.comboBoxPageSize);
            this.panelPager.Controls.Add(this.labelPage);
            this.panelPager.Controls.Add(this.buttonNext);
            this.panelPager.Controls.Add(this.buttonPrev);
            this.panelPager.Controls.Add(this.labelTotal);
            this.panelPager.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelPager.Location = new System.Drawing.Point(16, 624);
            this.panelPager.Name = "panelPager";
            this.panelPager.Size = new System.Drawing.Size(968, 40);
            this.panelPager.TabIndex = 1;
            this.comboBoxPageSize.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxPageSize.FormattingEnabled = true;
            this.comboBoxPageSize.Items.AddRange(new object[] {
            "10条/页",
            "20条/页",
            "50条/页"});
            this.comboBoxPageSize.Location = new System.Drawing.Point(94, 7);
            this.comboBoxPageSize.Name = "comboBoxPageSize";
            this.comboBoxPageSize.Size = new System.Drawing.Size(96, 26);
            this.comboBoxPageSize.TabIndex = 1;
            this.labelPage.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.labelPage.AutoSize = true;
            this.labelPage.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F);
            this.labelPage.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(98)))), ((int)(((byte)(102)))));
            this.labelPage.Location = new System.Drawing.Point(874, 9);
            this.labelPage.Name = "labelPage";
            this.labelPage.Size = new System.Drawing.Size(40, 24);
            this.labelPage.TabIndex = 4;
            this.labelPage.Text = "1/1";
            this.buttonNext.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonNext.FlatAppearance.BorderSize = 0;
            this.buttonNext.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonNext.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F);
            this.buttonNext.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(98)))), ((int)(((byte)(102)))));
            this.buttonNext.Location = new System.Drawing.Point(928, 4);
            this.buttonNext.Name = "buttonNext";
            this.buttonNext.Size = new System.Drawing.Size(36, 30);
            this.buttonNext.TabIndex = 3;
            this.buttonNext.Text = ">";
            this.buttonNext.UseVisualStyleBackColor = true;
            this.buttonPrev.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonPrev.FlatAppearance.BorderSize = 0;
            this.buttonPrev.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonPrev.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F);
            this.buttonPrev.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(98)))), ((int)(((byte)(102)))));
            this.buttonPrev.Location = new System.Drawing.Point(832, 4);
            this.buttonPrev.Name = "buttonPrev";
            this.buttonPrev.Size = new System.Drawing.Size(36, 30);
            this.buttonPrev.TabIndex = 2;
            this.buttonPrev.Text = "<";
            this.buttonPrev.UseVisualStyleBackColor = true;
            this.labelTotal.AutoSize = true;
            this.labelTotal.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F);
            this.labelTotal.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(98)))), ((int)(((byte)(102)))));
            this.labelTotal.Location = new System.Drawing.Point(0, 9);
            this.labelTotal.Name = "labelTotal";
            this.labelTotal.Size = new System.Drawing.Size(67, 24);
            this.labelTotal.TabIndex = 0;
            this.labelTotal.Text = "共 0 条";
            this.panelFilter.Controls.Add(this.panelActions);
            this.panelFilter.Controls.Add(this.buttonSearch);
            this.panelFilter.Controls.Add(this.comboBoxStatus);
            this.panelFilter.Controls.Add(this.labelStatus);
            this.panelFilter.Controls.Add(this.comboBoxType);
            this.panelFilter.Controls.Add(this.labelType);
            this.panelFilter.Controls.Add(this.textBoxCategoryName);
            this.panelFilter.Controls.Add(this.labelCategoryName);
            this.panelFilter.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelFilter.Location = new System.Drawing.Point(16, 16);
            this.panelFilter.Name = "panelFilter";
            this.panelFilter.Size = new System.Drawing.Size(968, 60);
            this.panelFilter.TabIndex = 0;
            this.panelActions.Controls.Add(this.buttonAddSetmealCategory);
            this.panelActions.Controls.Add(this.buttonAddDishCategory);
            this.panelActions.Controls.Add(this.buttonBatchDelete);
            this.panelActions.Dock = System.Windows.Forms.DockStyle.Right;
            this.panelActions.Location = new System.Drawing.Point(588, 0);
            this.panelActions.Name = "panelActions";
            this.panelActions.Size = new System.Drawing.Size(380, 60);
            this.panelActions.TabIndex = 8;
            this.buttonAddSetmealCategory.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonAddSetmealCategory.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(184)))), ((int)(((byte)(0)))));
            this.buttonAddSetmealCategory.FlatAppearance.BorderSize = 0;
            this.buttonAddSetmealCategory.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonAddSetmealCategory.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.buttonAddSetmealCategory.ForeColor = System.Drawing.Color.White;
            this.buttonAddSetmealCategory.Location = new System.Drawing.Point(268, 14);
            this.buttonAddSetmealCategory.Name = "buttonAddSetmealCategory";
            this.buttonAddSetmealCategory.Size = new System.Drawing.Size(104, 32);
            this.buttonAddSetmealCategory.TabIndex = 2;
            this.buttonAddSetmealCategory.Text = "新增套餐分类";
            this.buttonAddSetmealCategory.UseVisualStyleBackColor = false;
            this.buttonAddDishCategory.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonAddDishCategory.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(184)))), ((int)(((byte)(0)))));
            this.buttonAddDishCategory.FlatAppearance.BorderSize = 0;
            this.buttonAddDishCategory.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonAddDishCategory.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.buttonAddDishCategory.ForeColor = System.Drawing.Color.White;
            this.buttonAddDishCategory.Location = new System.Drawing.Point(160, 14);
            this.buttonAddDishCategory.Name = "buttonAddDishCategory";
            this.buttonAddDishCategory.Size = new System.Drawing.Size(104, 32);
            this.buttonAddDishCategory.TabIndex = 1;
            this.buttonAddDishCategory.Text = "新增菜品分类";
            this.buttonAddDishCategory.UseVisualStyleBackColor = false;
            this.buttonBatchDelete.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonBatchDelete.BackColor = System.Drawing.Color.White;
            this.buttonBatchDelete.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(223)))), ((int)(((byte)(230)))));
            this.buttonBatchDelete.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonBatchDelete.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F);
            this.buttonBatchDelete.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(98)))), ((int)(((byte)(102)))));
            this.buttonBatchDelete.Location = new System.Drawing.Point(52, 14);
            this.buttonBatchDelete.Name = "buttonBatchDelete";
            this.buttonBatchDelete.Size = new System.Drawing.Size(100, 32);
            this.buttonBatchDelete.TabIndex = 0;
            this.buttonBatchDelete.Text = "批量删除";
            this.buttonBatchDelete.UseVisualStyleBackColor = false;
            this.buttonSearch.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(49)))), ((int)(((byte)(51)))));
            this.buttonSearch.FlatAppearance.BorderSize = 0;
            this.buttonSearch.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonSearch.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.buttonSearch.ForeColor = System.Drawing.Color.White;
            this.buttonSearch.Location = new System.Drawing.Point(491, 14);
            this.buttonSearch.Name = "buttonSearch";
            this.buttonSearch.Size = new System.Drawing.Size(80, 32);
            this.buttonSearch.TabIndex = 7;
            this.buttonSearch.Text = "查询";
            this.buttonSearch.UseVisualStyleBackColor = false;
            this.comboBoxStatus.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxStatus.FormattingEnabled = true;
            this.comboBoxStatus.Items.AddRange(new object[] {
            "全部",
            "启用",
            "禁用"});
            this.comboBoxStatus.Location = new System.Drawing.Point(383, 18);
            this.comboBoxStatus.Name = "comboBoxStatus";
            this.comboBoxStatus.Size = new System.Drawing.Size(102, 26);
            this.comboBoxStatus.TabIndex = 6;
            this.labelStatus.AutoSize = true;
            this.labelStatus.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F);
            this.labelStatus.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(98)))), ((int)(((byte)(102)))));
            this.labelStatus.Location = new System.Drawing.Point(335, 19);
            this.labelStatus.Name = "labelStatus";
            this.labelStatus.Size = new System.Drawing.Size(50, 24);
            this.labelStatus.TabIndex = 5;
            this.labelStatus.Text = "状态:";
            this.comboBoxType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxType.FormattingEnabled = true;
            this.comboBoxType.Items.AddRange(new object[] {
            "全部",
            "菜品分类",
            "套餐分类"});
            this.comboBoxType.Location = new System.Drawing.Point(227, 18);
            this.comboBoxType.Name = "comboBoxType";
            this.comboBoxType.Size = new System.Drawing.Size(102, 26);
            this.comboBoxType.TabIndex = 4;
            this.labelType.AutoSize = true;
            this.labelType.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F);
            this.labelType.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(98)))), ((int)(((byte)(102)))));
            this.labelType.Location = new System.Drawing.Point(179, 19);
            this.labelType.Name = "labelType";
            this.labelType.Size = new System.Drawing.Size(50, 24);
            this.labelType.TabIndex = 3;
            this.labelType.Text = "类型:";
            this.textBoxCategoryName.Location = new System.Drawing.Point(87, 17);
            this.textBoxCategoryName.Name = "textBoxCategoryName";
            this.textBoxCategoryName.Size = new System.Drawing.Size(84, 28);
            this.textBoxCategoryName.TabIndex = 1;
            this.labelCategoryName.AutoSize = true;
            this.labelCategoryName.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F);
            this.labelCategoryName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(96)))), ((int)(((byte)(98)))), ((int)(((byte)(102)))));
            this.labelCategoryName.Location = new System.Drawing.Point(0, 19);
            this.labelCategoryName.Name = "labelCategoryName";
            this.labelCategoryName.Size = new System.Drawing.Size(86, 24);
            this.labelCategoryName.TabIndex = 0;
            this.labelCategoryName.Text = "分类名称:";
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 18F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.panelRoot);
            this.Name = "UcCategoryManage";
            this.Size = new System.Drawing.Size(1000, 680);
            this.panelRoot.ResumeLayout(false);
            this.panelTable.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewCategory)).EndInit();
            this.panelPager.ResumeLayout(false);
            this.panelPager.PerformLayout();
            this.panelFilter.ResumeLayout(false);
            this.panelFilter.PerformLayout();
            this.panelActions.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        private System.Windows.Forms.Panel panelRoot;
        private System.Windows.Forms.Panel panelTable;
        private System.Windows.Forms.DataGridView dataGridViewCategory;
        private System.Windows.Forms.Panel panelPager;
        private System.Windows.Forms.ComboBox comboBoxPageSize;
        private System.Windows.Forms.Label labelPage;
        private System.Windows.Forms.Button buttonNext;
        private System.Windows.Forms.Button buttonPrev;
        private System.Windows.Forms.Label labelTotal;
        private System.Windows.Forms.Panel panelFilter;
        private System.Windows.Forms.Panel panelActions;
        private System.Windows.Forms.Button buttonAddSetmealCategory;
        private System.Windows.Forms.Button buttonAddDishCategory;
        private System.Windows.Forms.Button buttonBatchDelete;
        private System.Windows.Forms.Button buttonSearch;
        private System.Windows.Forms.ComboBox comboBoxStatus;
        private System.Windows.Forms.Label labelStatus;
        private System.Windows.Forms.ComboBox comboBoxType;
        private System.Windows.Forms.Label labelType;
        private System.Windows.Forms.TextBox textBoxCategoryName;
        private System.Windows.Forms.Label labelCategoryName;
        private System.Windows.Forms.DataGridViewCheckBoxColumn colSelect;
        private System.Windows.Forms.DataGridViewTextBoxColumn colName;
        private System.Windows.Forms.DataGridViewTextBoxColumn colType;
        private System.Windows.Forms.DataGridViewTextBoxColumn colSort;
        private System.Windows.Forms.DataGridViewTextBoxColumn colStatus;
        private System.Windows.Forms.DataGridViewTextBoxColumn colUpdateTime;
        private System.Windows.Forms.DataGridViewLinkColumn colEdit;
        private System.Windows.Forms.DataGridViewLinkColumn colDelete;
        private System.Windows.Forms.DataGridViewLinkColumn colToggle;
    }
}

